export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const SET_ADD_LOCATION_BOOL = 'SET_ADD_LOCATION_BOOL';
export const SET_ADD_LOCATION_FORM_SUBMIT_STATUS =
  'SET_ADD_LOCATION_FORM_SUBMIT_STATUS';
