export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const SET_ADD_LOCATION_BOOL = 'SET_ADD_LOCATION_BOOL';
export const SET_FORM_SUBMIT_STATUS = 'SET_FORM_SUBMIT_STATUS';

export const SET_MAP_VIEWER_ADDRESS_INITIAL_STATE =
  'SET_MAP_VIEWER_ADDRESS_INITIAL_STATE';

export const SET_MAP_VIEWER_COORDINATES_INITIAL_STATE =
  'SET_MAP_VIEWER_COORDINATES_INITIAL_STATE';

export const SET_MAP_VIEWER_NEAR_ME_INITIAL_STATE =
  'SET_MAP_VIEWER_NEAR_ME_INITIAL_STATE';

export const SET_MAP_INITIAL_POINT = 'SET_MAP_INITIAL_POINT';
export const SET_MAP_FINAL_POINT = 'SET_MAP_FINAL_POINT';
